name: Docker Image CI

on: 
  push:
    branches: 
      - master
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
            
    - name: Build image
      run: docker build . --file Dockerfile --tag mlops_assign:latest
      
    - name: Push image
      run: |
        IMAGE_ID=docker.io/mlops_assign
        
        docker tag mlops_assign:latest $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
